# Generated by Django 2.2.1 on 2020-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default='???', max_length=20),
        ),
    ]
